try to run evaluate results

diff --git a/.github/workflows/analysis.yml b/.github/workflows/analysis.yml
--- a/.github/workflows/analysis.yml
+++ b/.github/workflows/analysis.yml
@@ -58,20 +58,20 @@ jobs:
         -whitespace/indent \
         . 1>CPPLINT_LOG.out 2>CPPLINT_ERRORS.out || true
 
+    - name: Evaluate result
+      run: |
+          error_string=$(tail -n 1 CPPLINT_LOG.out)
+          num_errors=$(echo "${error_string//[!0-9]/}")
+          echo Found $num_errors problems in the formatting
+          if [[ $num_errors -gt 5450 ]]; then
+            echo CPPLINT check failed!
+          exit $num_errors
+          fi
+          echo CPPLINT check succeeded
+
     - name: Archive Reports
       uses: actions/upload-artifact@v3
       if: always()
       with:
         name: CPPLINT_reports
         path: ./*.out
-
-    # - name: Evaluate result
-    #   run: |
-    #       error_string=$(tail -n 1 CPPLINT_LOG.out)
-    #       num_errors=$(echo "${error_string//[!0-9]/}")
-    #       echo Found $num_errors problems in the formatting
-    #       if [[ $num_errors -gt 5450 ]]; then
-    #         echo CPPLINT check failed!
-    #       exit $num_errors
-    #       fi
-    #       echo CPPLINT check succeeded
